#lang s-exp (planet dyoo/bf/language)

(plus)(plus)(plus)(plus)(plus) (plus)(plus)(plus)(plus)(plus)
(brackets
 (greater-than) (plus)(plus)(plus)(plus)(plus) (plus)(plus)
 (greater-than) (plus)(plus)(plus)(plus)(plus) (plus)(plus)(plus)(plus)(plus)
 (greater-than) (plus)(plus)(plus)
 (greater-than) (plus)
 (less-than)(less-than)(less-than)(less-than) (minus))           
(greater-than) (plus)(plus) (period)
(greater-than) (plus) (period)
(plus)(plus)(plus)(plus)(plus) (plus)(plus) (period)
(period)
(plus)(plus)(plus) (period)
(greater-than) (plus)(plus) (period)
(less-than)(less-than) (plus)(plus)(plus)(plus)(plus)
(plus)(plus)(plus)(plus)(plus) (plus)(plus)(plus)(plus)(plus) (period)
(greater-than) (period)
(plus)(plus)(plus) (period)
(minus)(minus)(minus)(minus)(minus) (minus) (period)
(minus)(minus)(minus)(minus)(minus) (minus)(minus)(minus) (period)
(greater-than) (plus) (period)
(greater-than) (period)